/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;
import crud_db.crud_db;
import javax.swing.JFrame; 
import javax.swing.JOptionPane;
/**
 *
 * @author ACER
 */
public class form_AhliWaris extends javax.swing.JFrame {
    crud_db mycrud;
    String fieldAhliWaris[]={"id_ahli_waris","keterangan","saksi1","saksi2","file_ktp1","file_ktp2","status","alasan","tgl"};
    String judulkolom[]={"ID AHLI WARIS","KETERANGAN","SAKSI 1","SAKSI 2","NIK 1","NIK 2","STATUS","ALASAN","TANGGAL"};
    int lebarkolom[]={};
    String Sql="SELECT * FROM ahli_waris";
    crud_db obj = new crud_db();
   
    /**
     * Creates new form form_AhliWaris
     */
    public form_AhliWaris() {
        initComponents();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.setLocationRelativeTo(null);
        mycrud=new crud_db();
        txt_jumlah.setText("Jumlah Data :" + String.valueOf(obj.jumlahRecord(Sql))); 
        
        // Inisialisasi tabel dengan judul kolom
        mycrud.settingJudulTabel(tbl_AhliWaris, judulkolom);

        // Tampilkan data dengan query yang benar
        mycrud.tampilTabel(tbl_AhliWaris, Sql, judulkolom);

        // Atur lebar kolom sesuai kebutuhan
        mycrud.settingLebarKolom(tbl_AhliWaris, lebarkolom);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        text_ahliwaris = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        text_keterangan = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        text_saksi1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        text_saksi2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        text_nik1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        text_nik2 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        text_status = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        text_alasan = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        text_tanggal = new javax.swing.JTextField();
        btn_simpanahliwaris = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_AhliWaris = new javax.swing.JTable();
        btn_ubahAhliWaris = new javax.swing.JButton();
        btn_hapusAhliWaris = new javax.swing.JButton();
        btn_clearAhliWaris1 = new javax.swing.JButton();
        btn_laporanAhliWaris2 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        text_cari = new javax.swing.JTextField();
        txt_jumlah = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(183, 220, 254));
        jPanel1.setToolTipText("");
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("FORM AHLI WARIS");

        jLabel2.setText("Kode Ahli Waris");

        jLabel3.setText("Keterangan");

        jLabel4.setText("Saksi 1");

        jLabel5.setText("Saksi 2");

        jLabel6.setText("NIK KTP Saksi 1");

        jLabel7.setText("NIK KTP Saksi 2");

        text_nik2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_nik2ActionPerformed(evt);
            }
        });

        jLabel8.setText("Satatus");

        jLabel9.setText("Alasan");

        jLabel10.setText("Tanggal");

        btn_simpanahliwaris.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_simpanahliwaris.setText("SIMPAN");
        btn_simpanahliwaris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanahliwarisActionPerformed(evt);
            }
        });

        tbl_AhliWaris.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID AHLI WAFRIS", "KETERANGAN", "SAKSI 1", "SAKSI 2", "NO KTP 1", "NO KTP 2", "STATUS", "ALASAN", "TANGGAL"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbl_AhliWaris.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_AhliWarisMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_AhliWaris);

        btn_ubahAhliWaris.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_ubahAhliWaris.setText("UBAH");
        btn_ubahAhliWaris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ubahAhliWarisActionPerformed(evt);
            }
        });

        btn_hapusAhliWaris.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_hapusAhliWaris.setText("HAPUS");
        btn_hapusAhliWaris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusAhliWarisActionPerformed(evt);
            }
        });

        btn_clearAhliWaris1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_clearAhliWaris1.setText("CLEAR");
        btn_clearAhliWaris1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearAhliWaris1ActionPerformed(evt);
            }
        });

        btn_laporanAhliWaris2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_laporanAhliWaris2.setText("LAPORAN");
        btn_laporanAhliWaris2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_laporanAhliWaris2ActionPerformed(evt);
            }
        });

        jLabel11.setText("CARI DATA");

        text_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_cariActionPerformed(evt);
            }
        });

        txt_jumlah.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_jumlah.setText("JUMLAH DATA : ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(37, 37, 37))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(text_saksi1, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                            .addComponent(text_keterangan)
                            .addComponent(text_nik1)
                            .addComponent(text_nik2)
                            .addComponent(text_status)
                            .addComponent(text_alasan)
                            .addComponent(text_tanggal)
                            .addComponent(text_saksi2)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(text_ahliwaris, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(261, 261, 261)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 648, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btn_simpanahliwaris, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(btn_ubahAhliWaris, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(btn_hapusAhliWaris, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_clearAhliWaris1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48)
                                .addComponent(btn_laporanAhliWaris2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(407, 407, 407)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(text_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txt_jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(text_ahliwaris, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(text_keterangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(text_saksi1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(text_saksi2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(text_nik1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_nik2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_alasan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_simpanahliwaris, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_ubahAhliWaris, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_hapusAhliWaris, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_clearAhliWaris1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_laporanAhliWaris2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(text_cari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_jumlah)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_simpanahliwarisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanahliwarisActionPerformed
        String fieldid[] = {"id_ahli_waris","keterangan","saksi1","saksi2","file_ktp1","file_ktp2","status","alasan","tgl"};
    String isi[] = {
        text_ahliwaris.getText(),
        text_keterangan.getText(),
        text_saksi1.getText(),
        text_saksi2.getText(),
        text_nik1.getText(),
        text_nik2.getText(),
        text_status.getText(),
        text_alasan.getText(),
        text_tanggal.getText()
    };

    // Memanggil metode SimpanDinamis melalui objek mycrud
        mycrud.SimpanDinamis("ahli_waris", fieldid, isi);
        System.out.println("Data telah disimpan.");
        
        // Refresh tabel agar data terbaru langsung muncul
        mycrud.tampilTabel(tbl_AhliWaris, Sql, judulkolom);

        // Set ulang lebar kolom setelah tabel di-refresh
        mycrud.settingLebarKolom(tbl_AhliWaris, lebarkolom);
    }//GEN-LAST:event_btn_simpanahliwarisActionPerformed

    
    private void text_nik2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_nik2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_nik2ActionPerformed

    private void btn_ubahAhliWarisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ubahAhliWarisActionPerformed
    try {
        if (
            (text_ahliwaris.getText().equals("")) &&
            (text_keterangan.getText().equals("")) &&
            (text_saksi1.getText().equals("")) &&
            (text_saksi2.getText().equals("")) &&
            (text_nik1.getText().equals("")) &&
            (text_nik2.getText().equals("")) &&
            (text_status.getText().equals("")) &&
            (text_alasan.getText().equals("")) &&
            (text_tanggal.getText().equals(""))
        ) {
            JOptionPane.showMessageDialog(this, "Silahkan Pilih Data yang Ingin di Ubah");
            tbl_AhliWaris.requestFocus();
        } else {
            // Menyiapkan field dan nilai yang akan diubah
            String fieldnya[] = {"keterangan", "saksi1", "saksi2", "file_ktp1", "file_ktp2", "status", "alasan", "tgl"};
            String isiFieldnya[] = {
                text_keterangan.getText(),
                text_saksi1.getText(),
                text_saksi2.getText(),
                text_nik1.getText(),
                text_nik2.getText(),
                text_status.getText(),
                text_alasan.getText(),
                text_tanggal.getText()
            };
           
            obj.UbahDinamis("ahli_waris", "id_ahli_waris", text_ahliwaris.getText(), fieldnya, isiFieldnya);
            JOptionPane.showMessageDialog(this, "Data Berhasil Diubah");
            mycrud.tampilTabel(tbl_AhliWaris, Sql, judulkolom);
            mycrud.settingLebarKolom(tbl_AhliWaris, lebarkolom);
        }
    } catch (Exception e) {
        System.err.println(e.toString());
    }
    }//GEN-LAST:event_btn_ubahAhliWarisActionPerformed

    private void btn_hapusAhliWarisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusAhliWarisActionPerformed
    try {
        if (
            (text_ahliwaris.getText().equals("")) &&
            (text_keterangan.getText().equals("")) &&
            (text_saksi1.getText().equals("")) &&
            (text_saksi2.getText().equals("")) &&
            (text_nik1.getText().equals("")) &&
            (text_nik2.getText().equals("")) &&
            (text_status.getText().equals("")) &&
            (text_alasan.getText().equals("")) &&
            (text_tanggal.getText().equals(""))
        ) {
            JOptionPane.showMessageDialog(this, "Silahkan Pilih Data yang Ingin Dihapus");
            tbl_AhliWaris.requestFocus();
        } else {
            // Mendapatkan id_ahli_waris dari text field
            String idAhliWaris = text_ahliwaris.getText();
            obj.HapusDinamis("ahli_waris", "id_ahli_waris", idAhliWaris);
            
            // Refresh tabel dan atur lebar kolom
            mycrud.tampilTabel(tbl_AhliWaris, Sql, judulkolom);
            mycrud.settingLebarKolom(tbl_AhliWaris, lebarkolom);
            
        }
    } catch (Exception e) {
        System.err.println(e.toString());
    }
    }//GEN-LAST:event_btn_hapusAhliWarisActionPerformed

    private void btn_clearAhliWaris1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearAhliWaris1ActionPerformed
        text_ahliwaris.setText(null);
        text_keterangan.setText(null);
        text_saksi1.setText(null);
        text_saksi2.setText(null);
        text_nik1.setText(null);
        text_nik2.setText(null);
        text_status.setText(null);
        text_alasan.setText(null);
        text_tanggal.setText(null);
        text_ahliwaris.requestFocus();
    }//GEN-LAST:event_btn_clearAhliWaris1ActionPerformed

    private void btn_laporanAhliWaris2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_laporanAhliWaris2ActionPerformed
    obj.tampilLaporan("src/laporan/laporan_ahli_waris.jrxml", "SELECT * FROM ahli_waris");
    }//GEN-LAST:event_btn_laporanAhliWaris2ActionPerformed

    private void tbl_AhliWarisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_AhliWarisMouseClicked
    try {
        int baris = tbl_AhliWaris.getSelectedRow();
        text_ahliwaris.setText(tbl_AhliWaris.getValueAt(baris, 0).toString());
        text_keterangan.setText(tbl_AhliWaris.getValueAt(baris, 1).toString());
        text_saksi1.setText(tbl_AhliWaris.getValueAt(baris, 2).toString());
        text_saksi2.setText(tbl_AhliWaris.getValueAt(baris, 3).toString());
        text_nik1.setText(tbl_AhliWaris.getValueAt(baris, 4).toString());
        text_nik2.setText(tbl_AhliWaris.getValueAt(baris, 5).toString());
        text_status.setText(tbl_AhliWaris.getValueAt(baris, 6).toString());
        text_alasan.setText(tbl_AhliWaris.getValueAt(baris, 7).toString());
        text_tanggal.setText(tbl_AhliWaris.getValueAt(baris, 8).toString());
    } catch (Exception e) {
        System.err.println(e.toString());
    }
    }//GEN-LAST:event_tbl_AhliWarisMouseClicked

    private void text_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_cariActionPerformed
    try {
        String SQL = "SELECT * FROM ahli_waris WHERE id_ahli_waris LIKE '%" + text_cari.getText() + "%' OR keterangan LIKE '%" + text_cari.getText() + "%'";
        
        // Judul kolom untuk tabel
        String judulKolom[] = {"ID AHLI WARIS", "KETERANGAN", "SAKSI 1", "SAKSI 2", "NIK 1", "NIK 2", "STATUS", "ALASAN", "TANGGAL"};
        
        // Lebar kolom disesuaikan
        int lebarKolom[] = {100, 200, 150, 150, 100, 100, 80, 150, 100};
        
        // Menampilkan data ke tabel
        mycrud.tampilTabel(tbl_AhliWaris, SQL, judulKolom);
        mycrud.settingLebarKolom(tbl_AhliWaris, lebarKolom);
    } catch (Exception e) {
        System.err.println("Error: " + e.toString());
    }
    }//GEN-LAST:event_text_cariActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form_AhliWaris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form_AhliWaris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form_AhliWaris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form_AhliWaris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form_AhliWaris().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_clearAhliWaris1;
    private javax.swing.JButton btn_hapusAhliWaris;
    private javax.swing.JButton btn_laporanAhliWaris2;
    private javax.swing.JButton btn_simpanahliwaris;
    private javax.swing.JButton btn_ubahAhliWaris;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_AhliWaris;
    private javax.swing.JTextField text_ahliwaris;
    private javax.swing.JTextField text_alasan;
    private javax.swing.JTextField text_cari;
    private javax.swing.JTextField text_keterangan;
    private javax.swing.JTextField text_nik1;
    private javax.swing.JTextField text_nik2;
    private javax.swing.JTextField text_saksi1;
    private javax.swing.JTextField text_saksi2;
    private javax.swing.JTextField text_status;
    private javax.swing.JTextField text_tanggal;
    private javax.swing.JLabel txt_jumlah;
    // End of variables declaration//GEN-END:variables
}
