/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;
import crud_db.crud_db;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author ACER
 */
public class form_pengaduan extends javax.swing.JFrame {
    crud_db mycrud;
    crud_db obj = new crud_db();
    String fieldpengaduan[]={"id_pengaduan","pengaduan","aksi"};
    String judulkolom[]={"ID PENGADUAN","PENGADUAN","AKSI"};
    int lebarkolom[]={100,250,200};
    String Sql="SELECT * FROM pengaduan";
    /**
     * Creates new form form_pengaduan
     */
    public form_pengaduan() {
        initComponents();
        this.setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        mycrud=new crud_db();
        txt_jumlah.setText("Jumlah Data :" + String.valueOf(obj.jumlahRecord(Sql))); 
        
        // Inisialisasi tabel dengan judul kolom
        mycrud.settingJudulTabel(tbl_pengaduan, judulkolom);

        // Tampilkan data dengan query yang benar
        mycrud.tampilTabel(tbl_pengaduan, Sql, judulkolom);

        // Atur lebar kolom sesuai kebutuhan
        mycrud.settingLebarKolom(tbl_pengaduan, lebarkolom);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        text_idPengaduan = new javax.swing.JTextField();
        text_pengaduan = new javax.swing.JTextField();
        text_aksi = new javax.swing.JTextField();
        btn_SimpanPengaduan = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_pengaduan = new javax.swing.JTable();
        btn_ubah = new javax.swing.JButton();
        btn_hapus = new javax.swing.JButton();
        btn_clear = new javax.swing.JButton();
        btn_laporan = new javax.swing.JButton();
        text_cari = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_jumlah = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(183, 220, 254));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("FORM PENGADUAN");

        jLabel2.setText("Id Pengaduan");

        jLabel3.setText("Pengaduan");

        jLabel4.setText("Aksi");

        text_idPengaduan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_idPengaduanActionPerformed(evt);
            }
        });

        text_aksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_aksiActionPerformed(evt);
            }
        });

        btn_SimpanPengaduan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_SimpanPengaduan.setText("SIMPAN");
        btn_SimpanPengaduan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SimpanPengaduanActionPerformed(evt);
            }
        });

        tbl_pengaduan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID PENGAJUAN", "PENGADUAN", "AKSI"
            }
        ));
        tbl_pengaduan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_pengaduanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_pengaduan);

        btn_ubah.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_ubah.setText("UBAH");
        btn_ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ubahActionPerformed(evt);
            }
        });

        btn_hapus.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_hapus.setText("HAPUS");
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });

        btn_clear.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_clear.setText("CLEAR");
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });

        btn_laporan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_laporan.setText("LAPORAN");
        btn_laporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_laporanActionPerformed(evt);
            }
        });

        text_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_cariActionPerformed(evt);
            }
        });

        jLabel5.setText("CARI DATA");

        txt_jumlah.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_jumlah.setText("JUMLAH DATA :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(btn_SimpanPengaduan, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(100, 100, 100)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(text_idPengaduan)
                                    .addComponent(text_pengaduan)
                                    .addComponent(text_aksi, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(btn_ubah)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_hapus)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btn_clear)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(text_cari)
                                    .addComponent(btn_laporan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(text_idPengaduan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(text_pengaduan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(text_aksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_ubah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_SimpanPengaduan)
                    .addComponent(btn_hapus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_clear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_laporan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_jumlah)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_SimpanPengaduanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SimpanPengaduanActionPerformed
    String fieldid[] ={"id_pengaduan","pengaduan","aksi"};
    String isi[] = {
            text_idPengaduan.getText(),
            text_aksi.getText(),
            text_pengaduan.getText()
    };
        mycrud.SimpanDinamis("pengaduan", fieldid, isi);
        System.out.println("Data telah disimpan."); 
        
        // Refresh tabel agar data terbaru langsung muncul
        mycrud.tampilTabel(tbl_pengaduan, Sql, judulkolom);

        // Set ulang lebar kolom setelah tabel di-refresh
        mycrud.settingLebarKolom(tbl_pengaduan, lebarkolom);
    }//GEN-LAST:event_btn_SimpanPengaduanActionPerformed

    private void text_aksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_aksiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_aksiActionPerformed

    private void text_idPengaduanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_idPengaduanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_idPengaduanActionPerformed

    private void btn_ubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ubahActionPerformed
        try {
            if (
                    (text_idPengaduan.getText().equals("")) &&
                    (text_pengaduan.getText().equals("")) && (text_aksi.getText().equals(""))
                ){
                JOptionPane.showMessageDialog(this, "Silahkan Pilih Data yang Ingin di Ubah");
                tbl_pengaduan.requestFocus();
            } else {
                String fieldnya[] ={"pengaduan","aksi"};
                String[] isiFieldnya = {
                    text_pengaduan.getText(),
                    text_aksi.getText()};
                obj.UbahDinamis("pengaduan", "id_pengaduan", text_idPengaduan.getText(), fieldnya, isiFieldnya);
                JOptionPane.showMessageDialog(this, "Data Berhasil Diubah");
                
                mycrud.tampilTabel(tbl_pengaduan, Sql, judulkolom);
                mycrud.settingLebarKolom(tbl_pengaduan, lebarkolom);
            }
        } catch  (Exception e) {
            System.err.println(e.toString());
        }
    }//GEN-LAST:event_btn_ubahActionPerformed

    private void tbl_pengaduanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_pengaduanMouseClicked
        try {
            int baris = tbl_pengaduan.getSelectedRow();
            text_aksi.setText(tbl_pengaduan.getValueAt(baris, 2).toString());
            text_idPengaduan.setText(tbl_pengaduan.getValueAt(baris, 0).toString());
            text_pengaduan.setText(tbl_pengaduan.getValueAt(baris, 1).toString());
        } catch (Exception e){
        }
    }//GEN-LAST:event_tbl_pengaduanMouseClicked

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        try {
            if (
                    (text_idPengaduan.getText().equals("")) &&
                    (text_pengaduan.getText().equals("")) && 
                    (text_aksi.getText().equals(""))
                )
            {
                JOptionPane.showMessageDialog(this, "Silahkan Pilih data yang Ingin dihapus");
                tbl_pengaduan.requestFocus();
            } else{
                String idPengaduan = text_idPengaduan.getText();
                obj.HapusDinamis("pengaduan", "id_pengaduan", idPengaduan);
                mycrud.tampilTabel(tbl_pengaduan, Sql, judulkolom);
                mycrud.settingLebarKolom(tbl_pengaduan, lebarkolom);
            }
        }
        catch  (Exception e) {
            System.err.println(e.toString());
        }
    }//GEN-LAST:event_btn_hapusActionPerformed

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        text_idPengaduan.setText(null);
        text_pengaduan.setText(null);
        text_aksi.setText(null);
        text_idPengaduan.requestFocus();
    }//GEN-LAST:event_btn_clearActionPerformed

    private void btn_laporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_laporanActionPerformed
        obj.tampilLaporan("src/laporan/laporan_pengaduan.jrxml", "SELECT * FROM pengaduan");
    }//GEN-LAST:event_btn_laporanActionPerformed

    private void text_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_cariActionPerformed
    try {
        // Query SQL untuk pencarian data
        String SQL = "SELECT * FROM pengaduan WHERE id_pengaduan LIKE '%" + text_cari.getText() + "%' OR pengaduan LIKE '%" + text_cari.getText() + "%'";
        
        // Judul kolom untuk tabel
        String judulkolom[] = {"ID PENGADUAN", "PENGADUAN", "AKSI"};
        
        // Lebar kolom disesuaikan
        int lebarKolom[] = {100, 300, 150}; // Disesuaikan dengan jumlah kolom dan kebutuhan
        
        // Menampilkan data ke tabel
        mycrud.tampilTabel(tbl_pengaduan, SQL, judulkolom);
        mycrud.settingLebarKolom(tbl_pengaduan, lebarKolom);
    } catch (Exception e) {
        // Menangkap dan mencetak kesalahan
        System.err.println("Error: " + e.toString());
    }
    }//GEN-LAST:event_text_cariActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form_pengaduan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form_pengaduan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form_pengaduan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form_pengaduan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form_pengaduan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_SimpanPengaduan;
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_laporan;
    private javax.swing.JButton btn_ubah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_pengaduan;
    private javax.swing.JTextField text_aksi;
    private javax.swing.JTextField text_cari;
    private javax.swing.JTextField text_idPengaduan;
    private javax.swing.JTextField text_pengaduan;
    private javax.swing.JLabel txt_jumlah;
    // End of variables declaration//GEN-END:variables
}
