/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;
import crud_db.crud_db;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author ACER
 */
public class form_penduduk extends javax.swing.JFrame {
    crud_db mycrud;
    String fieldpenduduk[]={"id_penduduk","nik","nama","tempat_lahir","tanggal_lahir","jenis_kelamin",
        "agama","status_perkawinan","pekerjaan","alamat","no_kode"};
    String judulkolom[]={"ID PENDUDUK","NIK","NAMA","TEMPAT LAHIR","TANGGAL LAHIR","JENIS KELAMIN","AGAMA",
    "STATUS PERKAWINAN","PEKERJAAN","ALAMAT","NO KODE"};
    int lebarkolom[]={100,100,100,100};
    String Sql="SELECT * FROM penduduk";
    crud_db obj = new crud_db();

    /**
     * Creates new form form_penduduk
     */
    public form_penduduk() {
        initComponents();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.setLocationRelativeTo(null);
        mycrud=new crud_db();
        txt_jumlah.setText("Jumlah Data :" + String.valueOf(obj.jumlahRecord(Sql))); 
        
        // Inisialisasi tabel dengan judul kolom
        mycrud.settingJudulTabel(tbl_penduduk, judulkolom);

        // Tampilkan data dengan query yang benar
        mycrud.tampilTabel(tbl_penduduk, Sql, judulkolom);

        // Atur lebar kolom sesuai kebutuhan
        mycrud.settingLebarKolom(tbl_penduduk, lebarkolom);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        text_idPenduduk = new javax.swing.JTextField();
        text_nik = new javax.swing.JTextField();
        text_nama = new javax.swing.JTextField();
        text_tempatLahir = new javax.swing.JTextField();
        text_tgllahir = new javax.swing.JTextField();
        text_jk = new javax.swing.JTextField();
        text_agama = new javax.swing.JTextField();
        text_statusPerkawinan = new javax.swing.JTextField();
        text_pekerjaan = new javax.swing.JTextField();
        text_alamat = new javax.swing.JTextField();
        text_noKode = new javax.swing.JTextField();
        btn_simpanPenduduk = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_penduduk = new javax.swing.JTable();
        btn_ubah_penduduk = new javax.swing.JButton();
        btn_hapus_penduduk = new javax.swing.JButton();
        btn_clear_penduduk = new javax.swing.JButton();
        btn_laporan_penduduk = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        text_cari = new javax.swing.JTextField();
        txt_jumlah = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(183, 220, 254));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("FORM PENDUDUK");

        jLabel2.setText("Id Penduduk");

        jLabel3.setText("NIK");

        jLabel4.setText("Nama");

        jLabel5.setText("Tempat Lahir");

        jLabel6.setText("Tanggal Lahir");

        jLabel7.setText("Jenis Kelamin");

        jLabel8.setText("Agama");

        jLabel9.setText("Status Perkawinan");

        jLabel10.setText("Pekerjaan");

        jLabel11.setText("Alamat");

        jLabel12.setText("Kode Pos");

        btn_simpanPenduduk.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_simpanPenduduk.setText("SIMPAN");
        btn_simpanPenduduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanPendudukActionPerformed(evt);
            }
        });

        tbl_penduduk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID PENDUDUK", "NIK", "NAMA", "TEMPAT LAHIT", "TANGGAL LAHIR", "JENIS KELAMIN", "AGAMA", "STATUS PERKAWINAN", "PEKERJAAN", "ALAMAT", "NO KODE"
            }
        ));
        tbl_penduduk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_pendudukMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_penduduk);

        btn_ubah_penduduk.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_ubah_penduduk.setText("UBAH");
        btn_ubah_penduduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ubah_pendudukActionPerformed(evt);
            }
        });

        btn_hapus_penduduk.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_hapus_penduduk.setText("HAPUS");
        btn_hapus_penduduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapus_pendudukActionPerformed(evt);
            }
        });

        btn_clear_penduduk.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_clear_penduduk.setText("CLEAR");
        btn_clear_penduduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clear_pendudukActionPerformed(evt);
            }
        });

        btn_laporan_penduduk.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_laporan_penduduk.setText("LAPORAN");
        btn_laporan_penduduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_laporan_pendudukActionPerformed(evt);
            }
        });

        jLabel13.setText("CARI DATA");

        text_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_cariActionPerformed(evt);
            }
        });

        txt_jumlah.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_jumlah.setText("JUMLAH DATA :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel6)
                        .addComponent(jLabel7))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel4)
                        .addComponent(jLabel5)
                        .addComponent(jLabel3)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(text_nik, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text_idPenduduk, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text_nama, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text_tempatLahir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text_tgllahir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text_jk, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(107, 107, 107)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(btn_laporan_penduduk))
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(text_noKode, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text_alamat, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text_pekerjaan, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text_statusPerkawinan, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text_agama, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(340, 340, 340))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(text_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn_simpanPenduduk, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(btn_ubah_penduduk)
                                .addGap(38, 38, 38)
                                .addComponent(btn_hapus_penduduk)
                                .addGap(56, 56, 56)
                                .addComponent(btn_clear_penduduk))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 883, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(text_agama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(text_statusPerkawinan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(text_pekerjaan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(text_alamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(text_noKode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(text_idPenduduk, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(text_nik, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(text_nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(text_tempatLahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(text_tgllahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(text_jk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_simpanPenduduk, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_ubah_penduduk, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_hapus_penduduk, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_clear_penduduk, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_laporan_penduduk, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_jumlah)
                .addGap(9, 9, 9))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_simpanPendudukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanPendudukActionPerformed
        String fieldid[] ={"id_penduduk","nik","nama","tempat_lahir","tanggal_lahir","jenis_kelamin","agama",
        "status_perkawinan","pekerjaan","alamat","no_kode"};
    String isi[] = {
            text_idPenduduk.getText(),
            text_nik.getText(),
            text_nama.getText(),
            text_tempatLahir.getText(),
            text_tgllahir.getText(),
            text_jk.getText(),
            text_agama.getText(),
            text_statusPerkawinan.getText(),
            text_pekerjaan.getText(),
            text_alamat.getText(),
            text_noKode.getText()
    };
    // TODO add your handling code here:
        mycrud.SimpanDinamis("penduduk", fieldid, isi);
        System.out.println("Data telah disimpan.");  
        
        
        // Refresh tabel agar data terbaru langsung muncul
        mycrud.tampilTabel(tbl_penduduk, Sql, judulkolom);

        // Set ulang lebar kolom setelah tabel di-refresh
        mycrud.settingLebarKolom(tbl_penduduk, lebarkolom);
    }//GEN-LAST:event_btn_simpanPendudukActionPerformed

    private void btn_ubah_pendudukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ubah_pendudukActionPerformed
    try {
        // Memeriksa apakah semua field terisi (semua kondisi harus true)
        if (
                text_idPenduduk.getText().equals("") &&
                text_nik.getText().equals("") &&
                text_nama.getText().equals("") &&
                text_tempatLahir.getText().equals("") &&
                text_tgllahir.getText().equals("") &&
                text_jk.getText().equals("") &&
                text_agama.getText().equals("") &&
                text_statusPerkawinan.getText().equals("") &&
                text_pekerjaan.getText().equals("") &&
                text_alamat.getText().equals("") &&
                text_noKode.getText().equals("")
            ){
            JOptionPane.showMessageDialog(this, "Silahkan Pilih Data yang Ingin di Ubah");
            tbl_penduduk.requestFocus();
        } else {
            // Menentukan field yang ingin diubah
            String fieldnya[] = {
                "nik", "nama", "tempat_lahir", "tanggal_lahir", "jenis_kelamin", 
                "agama", "status_perkawinan", "pekerjaan", "alamat", "no_kode"
            };

            // Isi field yang baru
            String[] isiFieldnya = {
                text_nik.getText(),
                text_nama.getText(),
                text_tempatLahir.getText(),
                text_tgllahir.getText(),
                text_jk.getText(),
                text_agama.getText(),
                text_statusPerkawinan.getText(),
                text_pekerjaan.getText(),
                text_alamat.getText(),
                text_noKode.getText()
            };
            obj.UbahDinamis("penduduk", "id_penduduk", text_idPenduduk.getText(), fieldnya, isiFieldnya);

            // Menampilkan pesan jika data berhasil diubah
            JOptionPane.showMessageDialog(this, "Data Penduduk Berhasil Diubah");

            // Menyegarkan tabel agar data yang baru langsung terlihat
            mycrud.tampilTabel(tbl_penduduk, Sql, judulkolom);
            mycrud.settingLebarKolom(tbl_penduduk, lebarkolom);
        }
    } catch (Exception e) {
        System.err.println(e.toString());
    }
    }//GEN-LAST:event_btn_ubah_pendudukActionPerformed

    private void tbl_pendudukMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_pendudukMouseClicked
    try {
        // Ambil baris yang dipilih
        int baris = tbl_penduduk.getSelectedRow();
        text_idPenduduk.setText(tbl_penduduk.getValueAt(baris, 0).toString());
        text_nik.setText(tbl_penduduk.getValueAt(baris, 1).toString());
        text_nama.setText(tbl_penduduk.getValueAt(baris, 2).toString());
        text_tempatLahir.setText(tbl_penduduk.getValueAt(baris, 3).toString());
        text_tgllahir.setText(tbl_penduduk.getValueAt(baris, 4).toString());
        text_jk.setText(tbl_penduduk.getValueAt(baris, 5).toString());
        text_agama.setText(tbl_penduduk.getValueAt(baris, 6).toString());
        text_statusPerkawinan.setText(tbl_penduduk.getValueAt(baris, 7).toString());
        text_pekerjaan.setText(tbl_penduduk.getValueAt(baris, 8).toString());
        text_alamat.setText(tbl_penduduk.getValueAt(baris, 9).toString());
        text_noKode.setText(tbl_penduduk.getValueAt(baris, 10).toString());
    } catch (Exception e) {
        System.err.println(e.toString());
    }
    }//GEN-LAST:event_tbl_pendudukMouseClicked

    private void btn_hapus_pendudukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapus_pendudukActionPerformed
    try {
        if (
                text_idPenduduk.getText().equals("") &&
                text_nik.getText().equals("") && 
                text_nama.getText().equals("") && 
                text_tempatLahir.getText().equals("") &&
                text_tgllahir.getText().equals("") &&
                text_jk.getText().equals("") &&
                text_agama.getText().equals("") &&
                text_statusPerkawinan.getText().equals("") &&
                text_pekerjaan.getText().equals("") &&
                text_alamat.getText().equals("") &&
                text_noKode.getText().equals("")
            ) {
            JOptionPane.showMessageDialog(this, "Silahkan Pilih Data yang Ingin Dihapus");
            tbl_penduduk.requestFocus();
        } else {
            String idPenduduk = text_idPenduduk.getText();
            obj.HapusDinamis("penduduk", "id_penduduk", idPenduduk);
            mycrud.tampilTabel(tbl_penduduk, Sql, judulkolom);
            mycrud.settingLebarKolom(tbl_penduduk, lebarkolom);
        }
    } catch (Exception e) {
        System.err.println(e.toString());
    }
    }//GEN-LAST:event_btn_hapus_pendudukActionPerformed

    private void btn_clear_pendudukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clear_pendudukActionPerformed
        text_idPenduduk.setText(null);
        text_nik.setText(null);
        text_nama.setText(null);
        text_tempatLahir.setText(null);
        text_tgllahir.setText(null);
        text_jk.setText(null);
        text_agama.setText(null);
        text_statusPerkawinan.setText(null);
        text_pekerjaan.setText(null);
        text_alamat.setText(null);
        text_noKode.setText(null);
        text_idPenduduk.requestFocus();
    }//GEN-LAST:event_btn_clear_pendudukActionPerformed

    private void btn_laporan_pendudukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_laporan_pendudukActionPerformed
        obj.tampilLaporan("src/laporan/laporan_penduduk.jrxml", "SELECT * FROM penduduk");
    }//GEN-LAST:event_btn_laporan_pendudukActionPerformed

    private void text_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_cariActionPerformed
    try {
        // Query SQL untuk pencarian data
        String SQL = "SELECT * FROM penduduk WHERE id_penduduk LIKE '%" + text_cari.getText() + "%' OR nama LIKE '%" + text_cari.getText() + "%'";
        
        // Judul kolom untuk tabel
        String judulkolom[] = {
            "ID PENDUDUK", "NIK", "NAMA", "TEMPAT LAHIR", "TANGGAL LAHIR", "JENIS KELAMIN",
            "AGAMA", "STATUS PERKAWINAN", "PEKERJAAN", "ALAMAT", "NO KODE"
        };
        
        // Lebar kolom disesuaikan
        int lebarKolom[] = {100, 150, 200, 150, 150, 100, 100, 150, 150, 200, 100};
        
        // Menampilkan data ke tabel
        mycrud.tampilTabel(tbl_penduduk, SQL, judulkolom);
        mycrud.settingLebarKolom(tbl_penduduk, lebarKolom);
    } catch (Exception e) {
        // Menangkap dan mencetak kesalahan
        System.err.println("Error: " + e.toString());
    }
    }//GEN-LAST:event_text_cariActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form_penduduk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form_penduduk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form_penduduk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form_penduduk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form_penduduk().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_clear_penduduk;
    private javax.swing.JButton btn_hapus_penduduk;
    private javax.swing.JButton btn_laporan_penduduk;
    private javax.swing.JButton btn_simpanPenduduk;
    private javax.swing.JButton btn_ubah_penduduk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_penduduk;
    private javax.swing.JTextField text_agama;
    private javax.swing.JTextField text_alamat;
    private javax.swing.JTextField text_cari;
    private javax.swing.JTextField text_idPenduduk;
    private javax.swing.JTextField text_jk;
    private javax.swing.JTextField text_nama;
    private javax.swing.JTextField text_nik;
    private javax.swing.JTextField text_noKode;
    private javax.swing.JTextField text_pekerjaan;
    private javax.swing.JTextField text_statusPerkawinan;
    private javax.swing.JTextField text_tempatLahir;
    private javax.swing.JTextField text_tgllahir;
    private javax.swing.JLabel txt_jumlah;
    // End of variables declaration//GEN-END:variables
}
