/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import crud_db.crud_db;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author ACER
 */
public class form_pengajuan extends javax.swing.JFrame {
    crud_db mycrud;
    crud_db obj = new crud_db();
    String fieldpengajuan[]={"id_pengajuan","layanan","status_pengajuan","kode_tracking"};
    String judulkolom[]={"ID PENGAJUAN","LAYANAN","STATUS PENGAJUAN","KODE TRACKING"};
    int lebarkolom[]={100,100,150,120};
    String Sql="SELECT * FROM pengajuan";
    /**
     * Creates new form form_pengajuan
     */
    public form_pengajuan() {
        initComponents();
        this.setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        mycrud=new crud_db();
        txt_jumlah.setText("Jumlah Data :" + String.valueOf(obj.jumlahRecord(Sql))); 
        
        // Inisialisasi tabel dengan judul kolom
        mycrud.settingJudulTabel(tbl_pengajuan, judulkolom);

        // Tampilkan data dengan query yang benar
        mycrud.tampilTabel(tbl_pengajuan, Sql, judulkolom);

        // Atur lebar kolom sesuai kebutuhan
        mycrud.settingLebarKolom(tbl_pengajuan, lebarkolom);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        text_idPengajuan = new javax.swing.JTextField();
        text_Layanan = new javax.swing.JTextField();
        text_status = new javax.swing.JTextField();
        text_kodeTracking = new javax.swing.JTextField();
        btn_SimpanPengaduan = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_pengajuan = new javax.swing.JTable();
        btn_ubah_pengajuan = new javax.swing.JButton();
        btn_hapus_pengajuan = new javax.swing.JButton();
        btn_clear_pengajuan = new javax.swing.JButton();
        btn_laporan_pengajuan = new javax.swing.JButton();
        text_cari = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_jumlah = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(183, 220, 254));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("PENGAJUAN");

        jLabel2.setText("Id Pengajuan");

        jLabel3.setText("Layanan");

        jLabel4.setText("Status");

        jLabel5.setText("Kode Tracking");

        text_Layanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_LayananActionPerformed(evt);
            }
        });

        text_kodeTracking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_kodeTrackingActionPerformed(evt);
            }
        });

        btn_SimpanPengaduan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_SimpanPengaduan.setText("SIMPAN");
        btn_SimpanPengaduan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SimpanPengaduanActionPerformed(evt);
            }
        });

        tbl_pengajuan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID PENGAJUAN", "LAYANAN", "STATUS", "KODE TRACKING"
            }
        ));
        tbl_pengajuan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_pengajuanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_pengajuan);

        btn_ubah_pengajuan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_ubah_pengajuan.setText("UBAH");
        btn_ubah_pengajuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ubah_pengajuanActionPerformed(evt);
            }
        });

        btn_hapus_pengajuan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_hapus_pengajuan.setText("HAPUS");
        btn_hapus_pengajuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapus_pengajuanActionPerformed(evt);
            }
        });

        btn_clear_pengajuan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_clear_pengajuan.setText("CLEAR");
        btn_clear_pengajuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clear_pengajuanActionPerformed(evt);
            }
        });

        btn_laporan_pengajuan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_laporan_pengajuan.setText("LAPORAN");
        btn_laporan_pengajuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_laporan_pengajuanActionPerformed(evt);
            }
        });

        text_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_cariActionPerformed(evt);
            }
        });

        jLabel6.setText("CARI DATA");

        txt_jumlah.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_jumlah.setText("JUMLAH DATA :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(102, 102, 102)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(text_idPengajuan)
                            .addComponent(text_Layanan)
                            .addComponent(text_status)
                            .addComponent(text_kodeTracking, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(214, 214, 214)
                        .addComponent(jLabel1)))
                .addContainerGap(72, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(33, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn_SimpanPengaduan, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_ubah_pengajuan)
                                .addGap(18, 18, 18)
                                .addComponent(btn_hapus_pengajuan)
                                .addGap(18, 18, 18)
                                .addComponent(btn_clear_pengajuan))
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(text_cari)
                            .addComponent(btn_laporan_pengajuan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(40, 40, 40))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(text_idPengajuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel1)))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(text_Layanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(text_status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(text_kodeTracking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_SimpanPengaduan, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_ubah_pengajuan, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_hapus_pengajuan, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_clear_pengajuan, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_laporan_pengajuan, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_cari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(9, 9, 9)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_jumlah)
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_SimpanPengaduanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SimpanPengaduanActionPerformed
        String fieldid[] ={"id_pengajuan","layanan","status_pengajuan","kode_tracking"};
    String isi[] = {
            text_idPengajuan.getText(),
            text_Layanan.getText(),
            text_status.getText(),
            text_kodeTracking.getText()
    };
        mycrud.SimpanDinamis("pengajuan", fieldid, isi);
        System.out.println("Data telah disimpan."); 
        
        // Refresh tabel agar data terbaru langsung muncul
        mycrud.tampilTabel(tbl_pengajuan, Sql, judulkolom);

        // Set ulang lebar kolom setelah tabel di-refresh
        mycrud.settingLebarKolom(tbl_pengajuan, lebarkolom);
    }//GEN-LAST:event_btn_SimpanPengaduanActionPerformed

    private void text_LayananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_LayananActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_LayananActionPerformed

    private void text_kodeTrackingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_kodeTrackingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_kodeTrackingActionPerformed

    private void btn_ubah_pengajuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ubah_pengajuanActionPerformed
                                              
    try {
        if (
            (text_idPengajuan.getText().equals("")) &&
            (text_Layanan.getText().equals("")) &&
            (text_status.getText().equals("")) &&
            (text_kodeTracking.getText().equals(""))
        ) {
            JOptionPane.showMessageDialog(this, "Silahkan Pilih Data yang Ingin di Ubah");
            tbl_pengajuan.requestFocus();
        } else {
            String fieldnya[] = {"layanan", "status_pengajuan", "kode_tracking"};
            String isiFieldnya[] = {
                text_Layanan.getText(),
                text_status.getText(),
                text_kodeTracking.getText()
            };
            obj.UbahDinamis("pengajuan", "id_pengajuan", text_idPengajuan.getText(), fieldnya, isiFieldnya);
            JOptionPane.showMessageDialog(this, "Data Berhasil Diubah");

            // Refresh tabel dan atur lebar kolom
            mycrud.tampilTabel(tbl_pengajuan, Sql, judulkolom);
            mycrud.settingLebarKolom(tbl_pengajuan, lebarkolom);
        }
    } catch (Exception e) {
        System.err.println(e.toString());
    }
    }//GEN-LAST:event_btn_ubah_pengajuanActionPerformed

    private void tbl_pengajuanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_pengajuanMouseClicked
    try {
        // Ambil baris yang dipilih
        int baris = tbl_pengajuan.getSelectedRow();
        text_idPengajuan.setText(tbl_pengajuan.getValueAt(baris, 0).toString());
        text_Layanan.setText(tbl_pengajuan.getValueAt(baris, 1).toString());
        text_status.setText(tbl_pengajuan.getValueAt(baris, 2).toString());
        text_kodeTracking.setText(tbl_pengajuan.getValueAt(baris, 3).toString());
    } catch (Exception e) {
        System.err.println(e.toString());
    }
    }//GEN-LAST:event_tbl_pengajuanMouseClicked

    private void btn_hapus_pengajuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapus_pengajuanActionPerformed
    try {
        if (
                (text_idPengajuan.getText().equals("")) && 
                (text_Layanan.getText().equals("")) && 
                (text_status.getText().equals("")) && 
                (text_kodeTracking.getText().equals(""))
            )
        {
            JOptionPane.showMessageDialog(this, "Silahkan Pilih data yang Ingin dihapus");
            tbl_pengajuan.requestFocus();
        } else {
            String id_pengajuan = text_idPengajuan.getText();
            obj.HapusDinamis("pengajuan", "id_pengajuan", id_pengajuan);
            mycrud.tampilTabel(tbl_pengajuan, Sql, judulkolom);
            mycrud.settingLebarKolom(tbl_pengajuan, lebarkolom);
        }
    } catch (Exception e) {
        System.err.println(e.toString());
    }
    }//GEN-LAST:event_btn_hapus_pengajuanActionPerformed

    private void btn_clear_pengajuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clear_pengajuanActionPerformed
        text_idPengajuan.setText(null);
        text_Layanan.setText(null);
        text_status.setText(null);
        text_kodeTracking.setText(null);
        text_idPengajuan.requestFocus();
    }//GEN-LAST:event_btn_clear_pengajuanActionPerformed

    private void btn_laporan_pengajuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_laporan_pengajuanActionPerformed
        obj.tampilLaporan("src/laporan/laporan_pengajuan.jrxml", "SELECT * FROM pengajuan");
    }//GEN-LAST:event_btn_laporan_pengajuanActionPerformed

    private void text_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_cariActionPerformed
    try {
        // Query SQL untuk pencarian data
        String SQL = "SELECT * FROM pengajuan WHERE id_pengajuan LIKE '%" + text_cari.getText() + "%' OR layanan LIKE '%" + text_cari.getText() + "%'";

        // Judul kolom untuk tabel
        String judulkolom[] = {"ID PENGAJUAN", "LAYANAN", "STATUS PENGAJUAN", "KODE TRACKING"};

        // Lebar kolom disesuaikan (disesuaikan dengan jumlah kolom yang ada)
        int lebarKolom[] = {100, 300, 150, 200}; // Menambahkan lebar untuk kolom 'KODE TRACKING'

        // Menampilkan data ke tabel
        mycrud.tampilTabel(tbl_pengajuan, SQL, judulkolom);
        
        // Mengatur lebar kolom tabel
        mycrud.settingLebarKolom(tbl_pengajuan, lebarKolom);
    } catch (Exception e) {
        // Menangkap dan mencetak kesalahan
        System.err.println("Error: " + e.toString());
    }
    }//GEN-LAST:event_text_cariActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form_pengajuan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form_pengajuan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form_pengajuan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form_pengajuan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form_pengajuan().setVisible(true);
            }
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_SimpanPengaduan;
    private javax.swing.JButton btn_clear_pengajuan;
    private javax.swing.JButton btn_hapus_pengajuan;
    private javax.swing.JButton btn_laporan_pengajuan;
    private javax.swing.JButton btn_ubah_pengajuan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_pengajuan;
    private javax.swing.JTextField text_Layanan;
    private javax.swing.JTextField text_cari;
    private javax.swing.JTextField text_idPengajuan;
    private javax.swing.JTextField text_kodeTracking;
    private javax.swing.JTextField text_status;
    private javax.swing.JLabel txt_jumlah;
    // End of variables declaration//GEN-END:variables
}

