/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;
import crud_db.crud_db;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
/**
 *
 * @author ACER
 */
public class form_dispensasinikah extends javax.swing.JFrame {
    crud_db mycrud;
    String fielddispensasinikah[]={"id_dispensasi_nikah","id_suami","id_istri","no_desa","no_kua"};
    String judulkolom[]={"ID DISPENSASI","NIK SUAMI","NIK ISTRI","NO SURAT DESA","NO SURAT KUA"};
    int lebarkolom[]={100,150,100,100};
    String Sql="SELECT * FROM dispensasi_nikah";
    crud_db obj = new crud_db();
    /**
     * Creates new form form_dispensasinikah
     */
    public form_dispensasinikah() {
        initComponents();
        this.setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        mycrud=new crud_db();
        txt_jumlah.setText("Jumlah Data :" + String.valueOf(obj.jumlahRecord(Sql))); 
        
        // Inisialisasi tabel dengan judul kolom
        mycrud.settingJudulTabel(tbl_dispensiNikah, judulkolom);

        // Tampilkan data dengan query yang benar
        mycrud.tampilTabel(tbl_dispensiNikah, Sql, judulkolom);

        // Atur lebar kolom sesuai kebutuhan
        mycrud.settingLebarKolom(tbl_dispensiNikah, lebarkolom);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        text_idDisepensasi = new javax.swing.JTextField();
        text_idSuami = new javax.swing.JTextField();
        text_idIstri = new javax.swing.JTextField();
        text_noDesa = new javax.swing.JTextField();
        text_noKUA = new javax.swing.JTextField();
        btn_SimpanFormDisepensasi = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_dispensiNikah = new javax.swing.JTable();
        btn_ubah_dispen = new javax.swing.JButton();
        btn_hapus_dispen = new javax.swing.JButton();
        btn_clear_dispen = new javax.swing.JButton();
        btn_laporan_dispensasi = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        text_cari = new javax.swing.JTextField();
        txt_jumlah = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(183, 220, 254));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("FORM DISEPENSASI NIKAH");

        jLabel2.setText("Id Disepensasi Nikah");

        jLabel3.setText("NIK Suami");

        jLabel4.setText("NIK Istri");

        jLabel5.setText("No Surat Desa");

        jLabel6.setText("No Surat KUA");

        text_idDisepensasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_idDisepensasiActionPerformed(evt);
            }
        });

        text_noKUA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_noKUAActionPerformed(evt);
            }
        });

        btn_SimpanFormDisepensasi.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_SimpanFormDisepensasi.setText("SIMPAN");
        btn_SimpanFormDisepensasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SimpanFormDisepensasiActionPerformed(evt);
            }
        });

        tbl_dispensiNikah.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID DISEPENSASI NIKAH", "NIK SUAMI", "NIK STRI", "NO SURAT DESA", "NO SURAT KUA"
            }
        ));
        tbl_dispensiNikah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_dispensiNikahMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_dispensiNikah);

        btn_ubah_dispen.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_ubah_dispen.setText("UBAH");
        btn_ubah_dispen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ubah_dispenActionPerformed(evt);
            }
        });

        btn_hapus_dispen.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_hapus_dispen.setText("HAPUS");
        btn_hapus_dispen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapus_dispenActionPerformed(evt);
            }
        });

        btn_clear_dispen.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_clear_dispen.setText("CLEAR");
        btn_clear_dispen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clear_dispenActionPerformed(evt);
            }
        });

        btn_laporan_dispensasi.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_laporan_dispensasi.setText("LAPORAN");
        btn_laporan_dispensasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_laporan_dispensasiActionPerformed(evt);
            }
        });

        jLabel7.setText("CARI DATA");

        text_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_cariActionPerformed(evt);
            }
        });

        txt_jumlah.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_jumlah.setText("JUMLAH DATA :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(234, 234, 234)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(text_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn_SimpanFormDisepensasi, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_ubah_dispen)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_hapus_dispen)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_clear_dispen)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_laporan_dispensasi)))
                        .addGap(21, 21, 21))
                    .addComponent(txt_jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(text_idDisepensasi, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                            .addComponent(text_idSuami)
                            .addComponent(text_idIstri)
                            .addComponent(text_noDesa)
                            .addComponent(text_noKUA))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(text_idDisepensasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(text_idSuami, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(text_idIstri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(text_noDesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(text_noKUA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_laporan_dispensasi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_clear_dispen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_hapus_dispen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_ubah_dispen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_SimpanFormDisepensasi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(text_cari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txt_jumlah)
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void text_idDisepensasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_idDisepensasiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_idDisepensasiActionPerformed

    private void text_noKUAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_noKUAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_noKUAActionPerformed

    private void btn_SimpanFormDisepensasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SimpanFormDisepensasiActionPerformed
        String fieldid[] ={"id_dispensasi_nikah","id_suami","id_istri","no_desa","no_kua"};
    String isi[] = {
            text_idDisepensasi.getText(),
            text_idIstri.getText(),
            text_idSuami.getText(),
            text_noDesa.getText(),
            text_noKUA.getText()
    };
    // TODO add your handling code here:
        mycrud.SimpanDinamis("dispensasi_nikah", fieldid, isi);
        System.out.println("Data telah disimpan.");   
        
        
        // Refresh tabel agar data terbaru langsung muncul
        mycrud.tampilTabel(tbl_dispensiNikah, Sql, judulkolom);

        // Set ulang lebar kolom setelah tabel di-refresh
        mycrud.settingLebarKolom(tbl_dispensiNikah, lebarkolom);
    }//GEN-LAST:event_btn_SimpanFormDisepensasiActionPerformed

    private void btn_ubah_dispenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ubah_dispenActionPerformed
    try {
        // Pastikan ada data yang dipilih di tabel
        if (
                (text_idDisepensasi.getText().equals("")) && (text_idSuami.getText().equals("")) && 
                (text_idIstri.getText().equals("")) && (text_noDesa.getText().equals("")) && 
                (text_noKUA.getText().equals(""))
            ){
            JOptionPane.showMessageDialog(this, "Data Silahkan Pilih Data yang Ingin Diubah");
            tbl_dispensiNikah.requestFocus(); // Fokus kembali ke tabel
        } else {
            // Menyusun field dan isi untuk update
            String fieldnya[] = {"id_suami", "id_istri", "no_desa", "no_kua"};
            String[] isiFieldnya = {
                text_idSuami.getText(),
                text_idIstri.getText(),
                text_noDesa.getText(),
                text_noKUA.getText()
            };
            // Panggil metode UbahDinamis untuk mengubah data berdasarkan ID
            obj.UbahDinamis("dispensasi_nikah", "id_dispensasi_nikah", text_idDisepensasi.getText(), fieldnya, isiFieldnya);
            JOptionPane.showMessageDialog(this, "Data Berhasil Diubah");

            // Refresh tabel agar data terbaru langsung muncul
            mycrud.tampilTabel(tbl_dispensiNikah, Sql, judulkolom);
            // Set ulang lebar kolom setelah tabel di-refresh
            mycrud.settingLebarKolom(tbl_dispensiNikah, lebarkolom);
        }
    } catch (Exception e) {
        System.err.println(e.toString());
    }
    }//GEN-LAST:event_btn_ubah_dispenActionPerformed

    private void tbl_dispensiNikahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_dispensiNikahMouseClicked
        try {
        // Ambil baris yang dipilih
        int baris = tbl_dispensiNikah.getSelectedRow();
        text_idDisepensasi.setText(tbl_dispensiNikah.getValueAt(baris, 0).toString());
        text_idSuami.setText(tbl_dispensiNikah.getValueAt(baris, 1).toString());
        text_idIstri.setText(tbl_dispensiNikah.getValueAt(baris, 2).toString());
        text_noDesa.setText(tbl_dispensiNikah.getValueAt(baris, 3).toString());
        text_noKUA.setText(tbl_dispensiNikah.getValueAt(baris, 4).toString());
        } catch (Exception e) {
            System.err.println(e.toString());
        }
    }//GEN-LAST:event_tbl_dispensiNikahMouseClicked

    private void btn_hapus_dispenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapus_dispenActionPerformed
        try {
            if (
                    (text_idDisepensasi.getText().equals("")) && (text_idSuami.getText().equals("")) &&
                    (text_idIstri.getText().equals("")) && (text_noDesa.getText().equals("")) &&
                    (text_noKUA.getText().equals(""))
                )
            {
                JOptionPane.showMessageDialog(this, "Silahkan Pilih data yang Ingin dihapus");
                tbl_dispensiNikah.requestFocus();
            } else {
                String id_dispensasi_nikah = text_idDisepensasi.getText();
                obj.HapusDinamis("dispensasi_nikah", "id_dispensasi_nikah", id_dispensasi_nikah);
                mycrud.tampilTabel(tbl_dispensiNikah, Sql, judulkolom);
                mycrud.settingLebarKolom(tbl_dispensiNikah, lebarkolom);
            }
        }
            catch  (Exception e) {
            System.err.println(e.toString());
        }
    }//GEN-LAST:event_btn_hapus_dispenActionPerformed

    private void btn_clear_dispenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clear_dispenActionPerformed
        text_idDisepensasi.setText(null);
        text_idSuami.setText(null);
        text_idIstri.setText(null);
        text_noDesa.setText(null);
        text_noKUA.setText(null);
        text_idDisepensasi.requestFocus();
    }//GEN-LAST:event_btn_clear_dispenActionPerformed

    private void btn_laporan_dispensasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_laporan_dispensasiActionPerformed
        obj.tampilLaporan("src/laporan/laporan_dispensasi.jrxml", "SELECT * FROM dispensasi_nikah");
    }//GEN-LAST:event_btn_laporan_dispensasiActionPerformed

    private void text_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_cariActionPerformed
    try {
        // Query SQL untuk pencarian data
        String SQL = "SELECT * FROM dispensasi_nikah WHERE id_dispensasi_nikah LIKE '%" + text_cari.getText() + "%' OR id_suami LIKE '%" + text_cari.getText() + "%'";
        
        // Judul kolom untuk tabel
        String judulkolom[] = {"ID DISPENSASI", "ID SUAMI", "ID ISTRI", "NO DESA", "NO KUA"};
        
        // Lebar kolom disesuaikan
        int lebarKolom[] = {100, 200, 150, 150, 100};
        
        // Menampilkan data ke tabel
        mycrud.tampilTabel(tbl_dispensiNikah, SQL, judulkolom);
        mycrud.settingLebarKolom(tbl_dispensiNikah, lebarKolom);
    } catch (Exception e) {
        // Menangkap dan mencetak kesalahan
        System.err.println("Error: " + e.toString());
    }
    }//GEN-LAST:event_text_cariActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form_dispensasinikah().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_SimpanFormDisepensasi;
    private javax.swing.JButton btn_clear_dispen;
    private javax.swing.JButton btn_hapus_dispen;
    private javax.swing.JButton btn_laporan_dispensasi;
    private javax.swing.JButton btn_ubah_dispen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_dispensiNikah;
    private javax.swing.JTextField text_cari;
    private javax.swing.JTextField text_idDisepensasi;
    private javax.swing.JTextField text_idIstri;
    private javax.swing.JTextField text_idSuami;
    private javax.swing.JTextField text_noDesa;
    private javax.swing.JTextField text_noKUA;
    private javax.swing.JLabel txt_jumlah;
    // End of variables declaration//GEN-END:variables
}